### ISSUE TITLE
Can't import Molecule-Incubator

### ISSUE THREAD

**Issue by Eliott-Guevel** [OpenSmock/Molecule-Incubator#1]
Can't import the Molecule-Incubator project while executing its installation script.

I get the following error message, it seems that some Roassal tools aren't present at a moment when they should
![erreur molecule incubator](https://github.com/OpenSmock/Molecule-Incubator/assets/76944457/9ee5405c-04e4-4e03-954d-f0eecdda9222)

Done on a fresh Pharo 11 VM (the latest 64-bit official distribution)

**Comment by labordep** [comment]
The error is: `Instance of MetacelloMCBaselineOfProjectSpec did not understand #package:constructor:`
